package uno.anahata.gemini.functions;

import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * A simple POJO to transport a list of file paths from a tool call back to the client.
 * The client application will then be responsible for reading these files and creating the appropriate
 * {@code com.google.genai.types.Part} objects to be sent in a subsequent user message.
 *
 * @author pablo
 */
@NoArgsConstructor
@AllArgsConstructor
public class MultiPartResponse {
    /**
     * A list of absolute file paths to the files (e.g., images) that were generated by the tool.
     */
    public List<String> filePaths = new ArrayList<>();

    @Override
    public String toString() {
        return "MultiPartResponse{" + "filePaths=" + filePaths + '}';
    }
}
